WebSubjectManagement/Models/DBConnection.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace WebSubjectManagement.Models
{
    public class DBConnection
    {
        string conn;
        public DBConnection()
        {
            conn = ConfigurationManager.ConnectionStrings["QLMonHoc"].ConnectionString;

        }
        public SqlConnection getConn()
        {
            return new SqlConnection(conn);
        }

    }
}

WebSubjectManagement/Models/MonHoc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace WebSubjectManagement.Models
{
    public class MonHoc
    {
        
        [Required(ErrorMessage = "Fill Infor please")]
        [Display(Name = "TEN Ma mon HOC:")]
        public int MaMH { get; set; }
        [Required(ErrorMessage = "Fill Inform please")]
        [Display(Name = "TenMH")]
        public string TenMH { get; set; }
        [Required(ErrorMessage = "Fill Inform please")]
        [Display(Name = "TCLT")]
        public int TCLT { get; set; }
        [Required(ErrorMessage = "Fill Inform please")]
        [Display(Name = "TCLH")]
        public int TCTH { get; set; }

        [Required(ErrorMessage = "Fill Inform please")]
        [Display(Name = "MaKhoa")]
        public string MaKhoa { get; set; }
      
    }
    public class ListMonHoc
        {
        DBConnection dBConnection;
        public ListMonHoc()
        {
            dBConnection = new DBConnection();
        }
        public List<MonHoc>getds(string MaMH)
        {
            string url;
            if(string.IsNullOrEmpty(MaMH))
            {
                url = "SELECT *FROM MONHOC";
            }
            else
            {
                url = "SELECT *FROM MONHOC WHERE MAMH=" + MaMH;
            }
            List<MonHoc> dsmonhoc = new List<MonHoc>();
            DataTable dt = new DataTable();
            SqlConnection conn = dBConnection.getConn();
            SqlDataAdapter da = new SqlDataAdapter(url, conn);
            conn.Open();
            da.Fill(dt);
            da.Dispose();
            conn.Close();
            MonHoc temp;
            for(int i=0;i<dt.Rows.Count;i++)
            {
                temp = new MonHoc();
                temp.MaMH = Convert.ToInt32(dt.Rows[i]["MaMH"].ToString());
                temp.TenMH = dt.Rows[i]["TenMH"].ToString();
                temp.TCLT = Convert.ToInt32(dt.Rows[i]["TCLT"].ToString());
                temp.TCTH = Convert.ToInt32(dt.Rows[i]["TCTH"].ToString());
                temp.MaKhoa = dt.Rows[i]["MAKHOA"].ToString();
                dsmonhoc.Add(temp);
            }
            return dsmonhoc;
        }
        public void InsertMH(MonHoc mh)
        {
            string url = 
             "Insert into MONHOC Values('" + mh.MaMH + "','" + mh.TenMH + "','" + mh.TCLT + "','" + mh.TCTH + "','" + mh.MaKhoa + "')";
            SqlConnection conn = dBConnection.getConn();
            SqlCommand cmd = new SqlCommand(url,conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            conn.Close();


        }
        public void EditMH(MonHoc mh)
        {
            string url = "UPDATE MONHOC SET TenMH='"+mh.TenMH+"',TCLT='"+mh.TCLT+"',TCTH='"+mh.TCTH+"',MaKhoa='"+mh.MaKhoa+"' where MaMH="+mh.MaMH;
            SqlConnection conn = dBConnection.getConn();
            SqlCommand cmd = new SqlCommand(url, conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            conn.Close();
        }
        public void DeleteMH(MonHoc mh)
        {
            string url = "DELETE FROM MONHOC where MaMH="+mh.MaMH; 
            SqlConnection conn = dBConnection.getConn();
            SqlCommand cmd = new SqlCommand(url, conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            conn.Close();

        }

        }
}

WebSubjectManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSubjectManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebSubjectManagement/Controllers/MonHocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSubjectManagement.Models;

namespace WebSubjectManagement.Controllers
{
    public class MonHocController : Controller
    {
        // GET: MonHoc
        public ActionResult Index(string strSearch)
        {
            ListMonHoc dsmonhoc = new ListMonHoc();
            List<MonHoc> obj = dsmonhoc.getds(string.Empty).OrderBy(x => x.TenMH).ToList();
            if(!String.IsNullOrEmpty(strSearch))
            {
                obj = obj.Where(x => x.TenMH.Contains(strSearch)).ToList();
            }
            return View(obj);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(MonHoc mh)
        {
            if (ModelState.IsValid)
            {
                ListMonHoc dsmonhoc = new ListMonHoc();
                dsmonhoc.InsertMH(mh);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(string id="")
        {
            ListMonHoc dsmonhoc = new ListMonHoc();
            List<MonHoc> obj = dsmonhoc.getds(id);
            return View(obj.FirstOrDefault());

        }
        [HttpPost]
        public ActionResult Edit(MonHoc mh)
        {
           
                ListMonHoc dsmonhoc = new ListMonHoc();
                dsmonhoc.EditMH(mh);
                return RedirectToAction("Index");

        }
        public ActionResult Details(string id="")
        {
            ListMonHoc dsmonhoc = new ListMonHoc();
            List<MonHoc> obj = dsmonhoc.getds(id);
            return View(obj.FirstOrDefault());
        }
        public ActionResult Delete(string id="")
        {
           
            ListMonHoc dsmonhoc = new ListMonHoc();
            List<MonHoc> obj = dsmonhoc.getds(id);
            return View(obj.FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(MonHoc mh)
        {
           
                ListMonHoc dsmonhoc = new ListMonHoc();
                dsmonhoc.DeleteMH(mh);
                return RedirectToAction("Index");
            
        }
    }
}

WebSubjectManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebSubjectManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebSubjectManagement/Views/Home/Index.cshtml
@model WebSubjectManagement.Models.MonHoc

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WebSubjectManagement/Views/MonHoc/Create.cshtml
@model WebSubjectManagement.Models.MonHoc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MonHoc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TCLT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TCLT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TCLT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TCTH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TCTH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TCTH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaKhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSubjectManagement/Views/MonHoc/Delete.cshtml
@model WebSubjectManagement.Models.MonHoc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonHoc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaMH)
            

        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaMH)
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TCLT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TCLT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TCTH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TCTH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaKhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKhoa)
        </dd>
       
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
           @Html.HiddenFor(Model=>Model.MaMH)
        </div>
    }
</div>

WebSubjectManagement/Views/MonHoc/Details.cshtml
@model WebSubjectManagement.Models.MonHoc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<h2>Details</h2>

<div>
    <h4>MonHoc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TCLT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TCLT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TCTH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TCTH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaKhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKhoa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaMH }, new { @class = "btn btn-primary" }) &nbsp;&nbsp;&nbsp;
    @Html.ActionLink("Delete", "Delete", new {id=Model.MaMH},new {@class="btn btn-danger"})
    @Html.ActionLink("Back to List", "Index")
</p>

WebSubjectManagement/Views/MonHoc/Edit.cshtml
@model WebSubjectManagement.Models.MonHoc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MonHoc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TCLT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TCLT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TCLT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TCTH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TCTH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TCTH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaKhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebSubjectManagement/Views/MonHoc/Index.cshtml
@model IEnumerable<WebSubjectManagement.Models.MonHoc>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaMH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenMH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TCLT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TCTH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaKhoa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaMH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenMH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TCLT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TCTH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaKhoa)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MaMH }, new { @class = "btn btn-primary" }) &nbsp;&nbsp;&nbsp;
            @Html.ActionLink("Details", "Details", new { id = item.MaMH }, new { @class = "btn btn-success" }) &nbsp;&nbsp;&nbsp;
            @Html.ActionLink("Delete", "Delete", new { id = item.MaMH }, new { @class = "btn btn-danger" })&nbsp;&nbsp;&nbsp;
        </td>
    </tr>
}

</table>

WebSubjectManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @using (Html.BeginForm("Index", "MonHoc", FormMethod.Post, new { @class = "navbar-form navbar-right" }))
            {
                <div class="form-group" ><input type="text" name="strSearch" placeholder="Tim Kiem Mon Hoc" class="form-control"/></div>
                <div class="form-group"><button type="submit" class="btn-default">Search</button> </div>
            }
                </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>